spring:
  datasource:
    url: jdbc:mysql://172.17.10.111:3306/shiro?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create